name: DEPLOY TO STAGING

on:
  push:
    branches:
      - master

jobs:
  app-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
            node-version: '12'
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: npm run build
